### ISSUE TITLE
Not getting any reading

### ISSUE THREAD

**Issue by hector305** [NorthernMan54/homebridge-dht#1]
hello, homekit is picking up the sensor however theres no reading, i ran sudo status homebridge and i get these errors
<img width="806" alt="screenshot 2016-10-31 02 45 22" src="https://cloud.githubusercontent.com/assets/23162784/19846320/941897ca-9f14-11e6-8f4a-3e9df1f22763.png">

**Comment by NorthernMan54** [comment]
Hector, looking at the output I see that the dht22 command didn't return anything. What happens when you run 'dht22' from the command line? Can you post that output.

Also looking back at the instructions, I missed the step to create a cputemp command, so have added it. If you don't want to see your raspberry pi cpu temperature, please use the updated example config.json. This will fix the cputemp error as well.
