### ISSUE TITLE
Recent homebridge update broken things?

### ISSUE THREAD

**Issue by SkyJohn** [NorthernMan54/homebridge-dht#10]
The recent update to home bridge (0.4.25) seems to have broken this, homebridge wont start with it installed.

Similar issue to this I think: https://github.com/nfarina/homebridge/issues/1433#issuecomment-322804542

**Comment by pdlove** [comment]
As a note over here... Some plugins had issue because Apple changed some characteristics on services with the IOS 11 releases. I've fixed HAP-NodeJS to simply give warnings when these are encountered. For the time being Apple isn't rejecting them, but you never know when they might start. Let me know if you need more information on how to resolve this.

**Comment by NorthernMan54** [comment]
@pdlove

Tks for the warning on the changes, I should be okay with making the fixes for this, but I will let you know if I need an assist.  I have been watching these changes for IOS 11 closely, as I maintain a forked version of hap-nodesjs that supports Alexa.   And I expect some challenges with accessory numbering as a result of your

**Comment by NorthernMan54** [comment]
@pdlove

Updating via mobile, and it went and closed it

Changes to aid and iid.

**Comment by pdlove** [comment]
The changes I made are only to the iids on the bridge and only when there is more than one service. It shouldn’t cause you any issues.

**Comment by NorthernMan54** [comment]
I found the issue, I was setting the serial number to "undefined".  It has been fixed and promoted.  Please update and try again

**Comment by SkyJohn** [comment]
Works now :)

Thanks for the quick update.
